-- CRIAR O BANCO COM 2 TABELAS

-- TABELA 1  CADASTRO
--  CATEGORIA DO GAME (1/N)

CREATE DATABASE games;
USE games;

CREATE TABLE jogos(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    ANO VARCHAR(100) NOT NULL,
    PLATAFORMA VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    DESENVOLVEDORA VARCHAR(100) NOT NULL,
-- MODO HARD
PRIMARY KEY(ID)
);

CREATE TABLE categoria(
    ID INT NOT NUL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ATIVO CHAR(1) NOT NULL,
    FK_JOGO_ID INT NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT CAT_JOGO FOREIGN KEY (FK_JOGO_ID) REFERENCES jogos (ID);

